version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/last_doit
    file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/last_doit
    pattern: '**'
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 3600
      runas: root
